services:
  app:
    container_name: appNotificacion
    image: notificacion/app:1.0.0
    build: .
    ports:
      - 8083:8083
    environment:
      - DATABASE_URL=jdbc:mysql://db:3306/bdProyectoSII
      - DATABASE_USERNAME=root
      - DATABASE_PASSWORD=12345  
    depends_on:
      - db
    networks:
      - microservicios_net

  db:
    container_name: db-notificacion
    image: mysql:8.0
    ports:
      - 3309:3306
    environment:
      MYSQL_ROOT_PASSWORD: 12345  
      MYSQL_PASSWORD: 12345
      MYSQL_DATABASE: bdProyectoSII
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - microservicios_net

volumes:
  db-data: {}

networks:
  microservicios_net:
    external: true
